version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: url-shortener-postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d  # Mount init script

  # Redis Database
  redis:
    image: redis:7
    container_name: url-shortener-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --save 60 1 --loglevel warning
  # URL Shortener API
  url-shortener:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: url-shortener-api
    restart: always
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/var/log/url-shortener

  # Cronjob for cleaning expired URLs
  url-cleaner:
    build:
      context: ./cron
      dockerfile: Dockerfile
    container_name: url-shortener-cron
    restart: always
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

volumes:
  postgres_data:
  redis_data: