auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096

common:
  path_prefix: /tmp/loki
  storage:
    filesystem:
      chunks_directory: /tmp/loki/chunks
      rules_directory: /tmp/loki/rules
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory
    instance_addr: 127.0.0.1

schema_config:
  configs:
    - from: 2025-01-01
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

storage_config:
  tsdb_shipper:
    active_index_directory: /tmp/loki/tsdb/active
    cache_location: /tmp/loki/tsdb/cache

compactor:
  working_directory: /tmp/loki/compactor
  delete_request_store: filesystem
  retention_enabled: true

limits_config:
  allow_structured_metadata: true

ruler:
  alertmanager_url: http://alertmanager:9093
