server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /var/lib/promtail/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
- job_name: url-shortener
  pipeline_stages:
    - json:
        expressions:
          level: level
          msg: error
          timestamp: timestamp
          type: type
          status: status
          latency: latency
          client_ip: client_ip
          method: method
          path: path

  static_configs:
    - targets:
        - localhost
      labels:
        job: url-shortener-api
        __path__: /var/log/url-shortener/*.log
