{
 "title": "Requests Overview",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Redirect Max Percentile Latency",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "max by(latency) (quantile_over_time(0.99, {filename=\"/var/log/url-shortener/url-shortener.log\", job=\"url-shortener-api\", service_name=\"url-shortener-api\"} | json | path !~ `/url.*` | level = `warn` | unwrap latency [1m]))",
     "legendFormat": "99 Percentile"
    },
    {
     "direction": "backward",
     "expr": "max by(latency) (quantile_over_time(0.90, {filename=\"/var/log/url-shortener/url-shortener.log\", job=\"url-shortener-api\", service_name=\"url-shortener-api\"} | json | path !~ `/url.*` | level = `warn` | unwrap latency [1m]))",
     "legendFormat": "90 Percentile"
    },
    {
     "direction": "backward",
     "expr": "max by(latency) (quantile_over_time(0.75, {filename=\"/var/log/url-shortener/url-shortener.log\", job=\"url-shortener-api\", service_name=\"url-shortener-api\"} | json | path !~ `/url.*` | level = `warn` | unwrap latency [1m]))",
     "legendFormat": "75 Percentile"
    }
   ]
  },
  {
   "title": "Maximum Percentile Latency",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "max by(latency) (quantile_over_time(0.99, {filename=\"/var/log/url-shortener/url-shortener.log\", job=\"url-shortener-api\", service_name=\"url-shortener-api\"} | json | level = `info` | path =~ `/url.*` | unwrap latency [1m]))",
     "legendFormat": "99 Percentile"
    },
    {
     "direction": "backward",
     "expr": "max by(latency) (quantile_over_time(0.90, {filename=\"/var/log/url-shortener/url-shortener.log\", job=\"url-shortener-api\", service_name=\"url-shortener-api\"} | json | level = `info` | path =~ `/url.*` | unwrap latency [1m]))",
     "legendFormat": "90 Percentile"
    },
    {
     "direction": "backward",
     "expr": "max by(latency) (quantile_over_time(0.75, {filename=\"/var/log/url-shortener/url-shortener.log\", job=\"url-shortener-api\", service_name=\"url-shortener-api\"} | json | level = `info` | path =~ `/url.*` | unwrap latency [1m]))",
     "legendFormat": "75 Percentile"
    }
   ]
  },
  {
   "title": "Error Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(status) (count_over_time({filename=\"/var/log/url-shortener/url-shortener.log\", job=\"url-shortener-api\", service_name=\"url-shortener-api\"} | json | status =~ `4..|5..` [$__auto]))"
    }
   ]
  },
  {
   "title": "Request Count",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(status) (count_over_time({filename=\"/var/log/url-shortener/url-shortener.log\", job=\"url-shortener-api\", service_name=\"url-shortener-api\"} | json | type = `GIN` [$__auto]))"
    }
   ]
  },
  {
   "title": "Top 10 CRUD Calls",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "targets": [
    {
     "direction": "backward",
     "expr": "topk(10, sum by(path) (count_over_time({filename=\"/var/log/url-shortener/url-shortener.log\", job=\"url-shortener-api\", service_name=\"url-shortener-api\"} | json | type = `GIN` | path =~ `/urls.*` [$__auto])))"
    }
   ]
  },
  {
   "title": "Top 10 Consumers IP",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
   "targets": [
    {
     "direction": "backward",
     "expr": "topk(10, sum by(client_ip) (count_over_time({filename=\"/var/log/url-shortener/url-shortener.log\", job=\"url-shortener-api\", service_name=\"url-shortener-api\"} | json | client_ip != `` [$__auto])))"
    }
   ]
  },
  {
   "title": "Top 10 Short URLs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "targets": [
    {
     "direction": "backward",
     "expr": "topk(10, sum by(path) (count_over_time({filename=\"/var/log/url-shortener/url-shortener.log\", job=\"url-shortener-api\", service_name=\"url-shortener-api\"} | json | type = `GIN` | path !~ `/urls.*` [$__auto])))"
    }
   ]
  }
 ]
}