// Code generated by mockery v2.51.1. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// URLService is an autogenerated mock type for the URLService type
type URLService struct {
	mock.Mock
}

// CreateShortURL provides a mock function with given fields: ctx, originalURL, expiry
func (_m *URLService) CreateShortURL(ctx context.Context, originalURL string, expiry *time.Time) (string, error) {
	ret := _m.Called(ctx, originalURL, expiry)

	if len(ret) == 0 {
		panic("no return value specified for CreateShortURL")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *time.Time) (string, error)); ok {
		return rf(ctx, originalURL, expiry)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *time.Time) string); ok {
		r0 = rf(ctx, originalURL, expiry)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *time.Time) error); ok {
		r1 = rf(ctx, originalURL, expiry)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewURLService creates a new instance of URLService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewURLService(t interface {
	mock.TestingT
	Cleanup(func())
}) *URLService {
	mock := &URLService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
